export const DISPLAY_ALERT = "SHOW_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

export const LOGOUT_USER = "LOGOUT_USER";
export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";

export const LOGIN_USER_BEGIN = "LOGIN_USER_BEGIN";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const ALL_STATE_BEGIN = "ALL_STATE_BEGIN";
export const ALL_STATE_SUCCESS = "ALL_STATE_SUCCESS";
export const ALL_STATE_ERROR = "ALL_STATE_ERROR";

export const ALL_CLIENTS_BEGIN = "ALL_CLIENTS_BEGIN";
export const ALL_CLIENTS_SUCCESS = "ALL_CLIENTS_SUCCESS";
export const ALL_CLIENTS_ERROR = "ALL_CLIENTS_ERROR";

export const ALL_PROVIDERS_BEGIN = "ALL_PROVIDERS_BEGIN";
export const ALL_PROVIDERS_SUCCESS = "ALL_PROVIDERS_SUCCESS";
export const ALL_PROVIDERS_ERROR = "ALL_PROVIDERS_ERROR";

export const GET_RECENT_BOOKING_BEGIN = "GET_RECENT_BOOKING_BEGIN";
export const GET_RECENT_BOOKING_SUCCESS = "GET_RECENT_BOOKING_SUCCESS";
export const GET_RECENT_BOOKING_ERROR = "GET_RECENT_BOOKING_ERROR";

export const GET_RECENT_PROVIDERS_BEGIN = "GET_RECENT_PROVIDERS_BEGIN";
export const GET_RECENT_PROVIDERS_SUCCESS = "GET_RECENT_PROVIDERS_SUCCESS";
export const GET_RECENT_PROVIDERS_ERROR = "GET_RECENT_PROVIDERS_ERROR";

export const SELECTED_BOOKINGS_VIEW_BEGIN = "SELECTED_BOOKINGS_VIEW_BEGIN";
export const SELECTED_BOOKINGS_VIEW_SUCCESS = "SELECTED_BOOKINGS_VIEW_SUCCESS";
export const SELECTED_BOOKINGS_VIEW_ERROR = "SELECTED_BOOKINGS_VIEW_ERROR";
